openapi: 3.0.0
info:
  title: Daily Quote, Daily Word, & Magic 8 Ball Web Service
  description: A random quote of the day, a random word of the day, and a magic 8 ball web service.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
  
paths:
  /quote:
    get:
      summary: The quote-of-the-day.
      responses:
        '200':
          description: A random quote-of-the-day is shown.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quote'
  /word:
    get:
      summary: The word-of-the-day.
      responses:
        '200':
          description: A random word-of-the-day is shown.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/definition'
  /magic:
    post:
      summary: Simulates a magic 8 ball. Ask it a question!
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/answer/properties/question'
      responses:
        '200':
          description: Sucessfully returned a random quote from the 8 ball.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/answer'
        '422':
          description:
            You must ask the magic 8 ball a question.
components:
  schemas:
    quote:
      properties:
        author:
          type: string
        quote:
          type: string
    definition:
      properties:
        word:
          type: string
        definition:
          type: string
    answer:
      properties:
        question:
          type: string
        answer:
          type: string