openapi: 3.0.0
info:
  title: Hello, REST
  description: A simple service that responds with "Hello, {NAME}".
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server

paths:
  /hello/{name}:
    get:
      summary: Responds with the "Hello, {NAME}".
      description: A simple demo service that simply responds with "Hello, {NAME}".
      parameters: 
        - name: name
          in: path
          required: true
          description: Your name.
          schema:
            type: string
      responses:
        '200':
          description: Hello, {NAME}
          content:
            application/json:
              schema:
                type: string