/**********************************************************************************************************************
 *  Name:           Dominick DeChristofaro
 *  Date:           08/08/2019
 *  Description:    Generate a random integer (1 - 100 inclusive), and have the user
 *                  guess until they find the random integer.  Display the number of guesses
 *                  required to find the random number.
 *********************************************************************************************************************/
package com.company;
import java.util.Scanner;
import java.util.Random;

public class HiLo {
    public static void main(String[] args) {

        // Create a random number for the program between 1 and 100 inclusive
        Random randomNumberObject = new Random();
        int lowInteger = 1;
        int highInteger = 101;
        int randomInteger = randomNumberObject.nextInt(highInteger - lowInteger) + lowInteger;
        int guessInteger = 0;
        int numOfGuesses = 1;

        // Create Scanner object for user input
        Scanner scan = new Scanner(System.in);

        // Display the welcome message
        // Prompt the user for their name to store in variable name
        System.out.println("Welcome to Hi-Low!");
        System.out.println("Please enter your name.");
        String name = scan.nextLine();

        // Display the rules
        System.out.println("OK, " + name + ", here are the rules:");
        System.out.println("You will guess a number between 1 and 100 (inclusive).");
        System.out.println("Continue guessing until you have the right number!");
        System.out.println(" ");
        System.out.println("Please guess your first number.");
        guessInteger = Integer.parseInt(scan.nextLine());

        // Do while the users guess is not equal to the random number generated by the computer
        while(guessInteger != randomInteger) {
            // If the guess was too high, guess again and increase the guess counter
            if (guessInteger > randomInteger) {
                System.out.println("Too high!");
                System.out.println("Please guess again.");
                guessInteger = Integer.parseInt(scan.nextLine());
                numOfGuesses++;
            }
            // If the guess was too low, guess again and increase the guess counter
            else if (guessInteger < randomInteger) {
                System.out.println("Too low!");
                System.out.println("Please guess again.");
                guessInteger = Integer.parseInt(scan.nextLine());
                numOfGuesses++;
            }
        }

        // When the user guesses correctly, congratulate the user on a correct guess and display
        // the number of guesses required to guess correctly.
        System.out.println("Congratulations, " + name + "! You win!");
        System.out.println("It took you " + numOfGuesses + " guesses to find my number!");
    }
}
